### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by miguelangel43** [JAlcocerT/R_Stocks#1]
Hello,

Great project! I was checking it out to draw some inspiration for a project of my own and noticed that the [link](https://jalcocert.github.io/R_Stocks/) appears to be broken.

Keep up the good work!

<img width="743" alt="Screen Shot 2024-02-08 at 12 36 07 PM" src="https://github.com/JAlcocerT/R_Stocks/assets/50675302/d018e347-b23a-4f73-b9c2-80724e59df78">

**Comment by JAlcocerT** [comment]
Hello @miguelangel43 ,

You can deploy the RStocks locally with docker, please check the [deploy me folder](https://github.com/JAlcocerT/R_Stocks/tree/main/Z_Deploy_Me)

Thanks for your interest in the project!

Regards,
